[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "netlify-plugin-cache"

[build.environment]
  NODE_VERSION = "14"

[dev]
  command = "npm run start"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
